#!/usr/bin/perl
use strict;
use lib qw(lib);
use POE qw(Component::Server::FTP);
use Filesys::Virtual::SSH;

my $host = shift || 'switch.work.fotango.com';
my $port = shift || 2112;
print "Republishing $host on ftp://localhost:$port/\n";
POE::Component::Server::FTP->spawn(
    ListenPort      => $port,
    FilesystemClass => 'Filesys::Virtual::SSH',
    FilesystemArgs  => {
        host      => $host,
        root_path => '/',
        cwd       => '/',
        home_path => '/home',
    },
    # use 0 to disable these Limits
    DownloadLimit   => 0,
    UploadLimit     => 0,
    LimitSceme      => 'ip',  # ip or per (connection)
    LogLevel        => 4,     # 4=debug, 3=less info, 2=quiet, 1=really quiet
    TimeOut         => 120,   # Connection Timeout
   );

$poe_kernel->run();
